version: '3'

services:
  findcm-next-app:
    container_name: findcm-next-app
    command: pnpm run dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    volumes:
      - ./:/app
      - ./public:/app/public
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

networks:
  my_network:
    external: true